//! `ObservationSource` implementations, per ADR-0005: one source per
//! platform/signal-type pair, each declaring the minimum privacy level it may run
//! at.
//!
//! Platform coverage in this crate, and why:
//!
//! - **Linux** (`linux` module): implemented and tested against a real X11 display
//!   — this dev environment (WSLg) actually has one (`DISPLAY=:0`), so
//!   [`linux::ActiveWindowSource`] and [`linux::FileOperationSource`] are exercised
//!   against real X11/inotify in their test suites, not mocks.
//! - **macOS** (`macos` module, `#[cfg(target_os = "macos")]`): written against the
//!   real APIs named in `docs/roadmap/02-technology-choices.md` (`NSWorkspace`,
//!   `AXUIElement`, `CGWindowListCopyWindowInfo`), but **not compiled or tested in
//!   this environment** — there is no macOS toolchain/SDK here. `cfg`-gating means
//!   it simply isn't part of a Linux build, which is the correct, honest way to
//!   exclude platform code this environment can't verify, as opposed to leaving a
//!   `todo!()` stub in its place.
//! - **Windows** (`windows` module, `#[cfg(target_os = "windows")]`): same
//!   situation for its `active_window`, `clipboard`, and `shortcuts` submodules
//!   — written against Win32 (`GetForegroundWindow`, clipboard,
//!   `RegisterHotKey`) but not compiled or tested. `windows::file_ops` is lower
//!   risk: it's built on the same cross-platform `notify` crate Linux's
//!   `file_ops` uses, so it carries no hand-written Win32 FFI of its own.
//!
//! - **Deep-mode screenshot capture** (`screenshot` module, cross-platform, not
//!   `cfg`-gated): the first real producer of Level 4 ("Maximum assistance")
//!   content, via the actively-maintained [`xcap`](https://crates.io/crates/xcap)
//!   crate rather than three hand-rolled per-OS backends. Verified for real
//!   against the same Xvfb X11 display Linux's other sources use (see
//!   `screenshot`'s tests) — the macOS/Windows code paths inside `xcap` itself
//!   are not exercised here, the same disclosed gap as this crate's other
//!   non-Linux code below. Building this crate on Linux needs a handful of
//!   extra system `-dev` packages `xcap` pulls in for screen-recording support
//!   this source never uses (see `../README.md` and `screenshot.rs`'s doc
//!   comment) — the one place this crate is no longer "zero system
//!   dependencies beyond what `cargo` fetches."
//!
//! - **Browser bridge** (`browser_bridge` module, cross-platform, not
//!   `cfg`-gated, like `screenshot`): [`BrowserBridgeSource`] is the extension
//!   bridge this doc comment used to describe as unbuilt — there is still no
//!   OS-level API for "which domain is the foreground browser tab showing," so
//!   this signal genuinely does require a browser-extension component
//!   (`apps/browser-extension`, Manifest V3, Chrome/Chromium-based browsers —
//!   Firefox is a disclosed follow-up, see that extension's README). This
//!   source is the consumption side that module's earlier doc comment
//!   anticipated: it runs a local HTTP server bound to `127.0.0.1` only (never
//!   `0.0.0.0`), authenticated by a per-install bearer token (generated by
//!   `apps/desktop/src-tauri`, pasted once into the extension's options page —
//!   not CORS or the loopback binding alone, which don't stop another local
//!   process from connecting), that the extension's background service worker
//!   posts to whenever the active tab's hostname (Level 2) or title (Level 3)
//!   changes. Verified for real in this environment: `browser_bridge`'s tests
//!   drive an actual `tiny_http` server bound to an OS-chosen loopback port
//!   over a real `TcpStream`, not a mock of the HTTP layer. The extension's own
//!   background-script/manifest code is not exercised here (no real browser in
//!   this sandbox) — its pure hostname/title-extraction logic is unit-tested
//!   under Node instead (see `apps/browser-extension/test`).
//!
//! One signal source named in `docs/design/05-privacy-model.md` §1 is still
//! deliberately **not** implemented anywhere in this crate, and that gap is
//! disclosed rather than papered over with a stub:
//!
//! - **Global keyboard shortcut capture** — implementing this on Linux means an
//!   X11 global key grab (`XGrabKey`), which intercepts that key combo
//!   session-wide. Installing one automatically in a shared development sandbox
//!   would risk interfering with whoever/whatever else is using this X session.
//!   The correct real implementation is written in `linux::shortcuts`, but it is
//!   opt-in (never auto-started) and its integration test is `#[ignore]`d for the
//!   same "don't do this by default in a shared environment" reason the real
//!   OS-vault test in `hiddensteps-security` is.

mod browser_bridge;
mod screenshot;
mod source;

pub use browser_bridge::BrowserBridgeSource;
pub use screenshot::ScreenshotSource;
pub use source::{ObservationSource, PollError};

#[cfg(target_os = "linux")]
pub mod linux;

#[cfg(target_os = "macos")]
pub mod macos;

#[cfg(target_os = "windows")]
pub mod windows;
